#!/usr/bin/env bash

docker exec -e MYSQL_PWD=debezium -it debezium_hive_kafka_mysql_1 /bin/bash -c \
"mysql -uroot -e \"GRANT ALL PRIVILEGES ON nw.* TO 'debezium'@'%'; CREATE DATABASE IF NOT EXISTS nw;\""
