#!/usr/bin/env bash

# Create nw database and grant all permissions to the user debezium
echo "Creating 'nw' database in MySQL..."
docker exec -e MYSQL_PWD=debezium -it debezium_hive_kafka-mysql-1 /bin/bash -c \
"mysql -uroot -e \"GRANT ALL PRIVILEGES ON nw.* TO 'debezium'@'%'; CREATE DATABASE IF NOT EXISTS nw;\""

# Copy the Kafka handler jar to HDFS. Required for executing queries with joins.
# Queries are submitted as jobs to HDFS.
echo "Uploading Kafka handler binary to Hive..."
docker-compose exec hive /bin/bash -c \
"hdfs dfs -mkdir -p /opt/hive/lib && hdfs dfs -copyFromLocal /opt/hive/lib/kafka-handler-3.1.3000.7.2.0.2-2.jar /opt/hive/lib/"

echo "init_all complete."
